### PR TITLE
UNO-205: Fire an event on a successful remote delivery publishing lookup

### PR DESCRIPTION
**Pull request by SergiiTao**
Ticket: [UNO-205](https://oat-sa.atlassian.net/browse/UNO-205)

taoUdir needs this event in order to match remote delivery id with user who tun publishing

### CODE REVIEW

**Comment by Alroniks** [comment]
Indeed. It is almost the same what @Yury-Razhkou did. Proper link to PR is #54, it seems @wazelin is wrong a little with PR id.

**Comment by SergiiTao** [comment]
> It looks like #54 does a very similar thing.

not really.
in #54 we have a new event with id for local delivery.
I created an event with parameters of the remote delivery.

**Comment by Yury-Razhkou** [comment]
> > It looks like #54 does a very similar thing.
> 
> not really.
> in #54 we have a new event with id for local delivery.
> I created an event with parameters of the remote delivery.

Local delivery id we can get from `DeliveryCreatedEvent`. `NGDeliveryCreatedEvent` was created to handle NG delivery id. According to the original task for #54  , we need to provide NG delivery id to the endpoint.

**Comment by SergiiTao** [comment]
> > > It looks like #54 does a very similar thing.
> > 
> > 
> > not really.
> > in #54 we have a new event with id for local delivery.
> > I created an event with parameters of the remote delivery.
> 
> Local delivery id we can get from `DeliveryCreatedEvent`. `NGDeliveryCreatedEvent` was created to handle NG delivery id. According to the original task for #54 , we need to provide NG delivery id to the endpoint.

looks like PasP going to be notified by handling `DeliveryCreatedEvent` 
`NGDeliveryCreatedEvent` from #54 will be fired after `DeliveryCreatedEvent` 
it is a bit too late for my stuff

**Pull request merged**
